name: Env & Secrets

on: 
  workflow_dispatch:

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
      - name: Try to show my vars and secrets content
        run: |
          echo Global Secret ${{ secrets.GLOBAL__SECRET }}
          echo My Secret ${{ secrets.MY_SECRET }}
          echo My Variable ${{ vars.MY_WEBSITE }}
