name: Manual Events

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: my-artifact
          path: hol
          retention-days: 30

      - uses: ./.github/workflows/reusable-workflow.yml
        with: 
          my-input: ${{ inputs.environment }}

