name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push, workflow_dispatch]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello 🖐️"
